language: node_js
node_js:
- '4.1'
script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/indigo-lab/geonamesjp_vs_yan.git
  - secure: BZ5jwlhKe+CHlWPYEGogUiPdFcKIp7paIrEaJdaghUJL7NZnUtLVvq91VAOD4R2CmTxPvNLH8WcmX9cl+sl1YmYRFrr1zW5uD4xKwg5eVivd/lt55ijnm8JqsKwMTNL4H72WNtBMf5sLYUXXktUqQUFw5+xsmqZv1oLJt+wMHpiBeHyrfjEpQJ9kJRjMmwUFq7kzWtgxl0MSnAm9Xfx/F5FTpKnRmG2yZKjTkXZaZHPJZabKPLsFnpyMRTmcf6/t7I6yZOLvAYxbz1YJkQ4c8tu8/073Zdg2ur/nzXMv7umhVpr2SLodfheXYURtHeL2YIOP6LY+K8xHK2zLXV99fuDobAnlFKD6B78nazWZ7oSWPFwS7PcB001pYNY8KeST2frp4KQiF4vCsB0WzLFjdWMCIgyJShXrTDH2HBmQs6qwD7Y6tI+rh+uWMtTTtaRTKmjiOOzpXJ7lqDm9SipXnGoKbQOm2jeBZegY3+yPSw+9dFwDGp0mU2QE6ZQAjS/88fPY4UlC8TfNAVTtrAbD6wvRGm287/gak/kwBQuCCR9LFb0HaftYzr1J4Foaarm4NGY27b2NAVJTHVAHts+Y2gCbc7aEXRVDJDGZUzDbXvASk0ZudmPjnDwbjEHWWvxzVxirLHlztczIAPagb5QXtkkYdCwsLFnAcl/53BI02xs=
