language: node_js
node_js:
- '4.1'
script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/indigo-lab/geonamesjp_vs_yan.git
  - secure: aJ8qQgeKPm3naxIugVCpw9F2iODUMDb11d9Wtm6C6GfmTrhX99u4vZAo8nC+Hj1mB+btA91LJ36iBULBaBBOOkUg1dR4Yj4WfShGmqpVKS2xMXY0ggwpGuOqNuj0HJmnznuDQLnjRrPEoBy/U2x1hBAJnABzRWVTbvU90GZT0g7f0OgdLaxYDfEBLx7+zBsySiR/K1Nv4XfdXGa+kVC/ZnzktJkmGsKYI1Fy0YQWoUgNhMDYiYSlq+Cay2RUd4WZvQvasb5K4hIqD1AF2t46oiH8CH4B4WpWvIFY4+vP3imMqy4/jE4Bps4KixKM9gvHKc1bprs0y4UGRAMmlZtepp8B6cn610QodKobfRrQP7svjRoTozyDn4mDvydTrSt77W6AU6HmMZ/TUvNBDgZElZgi5JTX74qIYPd08Q5bqqx+bI7hAmk077/dRILrCZ2Hh+eRRsMMx15CoW3ymQ7IoOdHaL11DBS9rds+As+R96+qWQMeJjE3gRe4J7Xq6VwJrq8+kehzd6rWuJp1OHqT0FbOQJUfnDRiPOsTHxPLZ+eaBcP8RHsnakSKcldSGPwxo4OcyuGewzDX9gopOkGM5druVwnKCtHQeYOPWBuVQJzTmcIk+N3PNhswwG/J95cElZyxnh5gTpc2vXrTDktQs3636MGN+KmQiaBXzBkGv/U=
